name: "godot-ci export"
on: 
  push:
    branches:
      - publish

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: fort
  PROJECT_PATH: fort
  ITCH_USER: happyearthbytes
  ITCH_GAME: fort
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    permissions: write-all
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../build/web/index.html
      - name: List all files
        run: |
          find .
      - name: Deploy to itch.io 🚀
        uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          CHANNEL: web
          PACKAGE: build/web