run-name: Do a Secreter by @${{ github.actor }}
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:

  # passing the secret to a nested reusable workflow
  pass-secret-to-workflow:
    uses: ./.github/workflows/builder.yml
    secrets:
       token: ${{ secrets.access-token }}

  # pass-secret-to-action:
  #   runs-on: ubuntu-latest
  #   steps:
  #   # passing the secret to an action
  #     - name: Pass the received secret to an action
  #       uses: ./.github/actions/build.yml
  #       with:
  #         token: ${{ secrets.access-token }}
